title: Ethan L - Puma
accent_image: /PEL2024Banner.jpeg
accent_color: rgb(79,177,186)
favicon: /icon.png
apple_touch_icon: /icon.png
remote_theme: hydecorp/hydejack@v9.1.6
plugins:
  - jekyll-include-cache
baseurl: /pel2024
menu:
 - title: Home
   url: /
 - title: Campfires
   url: /campfires.html
 - title: Tenderfoot
   url: /tenderfoot.html
 - title: Badge Clearing
   url: /badge-clearing
hydejack:
  dark_mode:
    dynamic: false
    sunrise: 6
    sunset:  18
    icon:    true
    always:  false
collections:
  featured_categories:
    permalink:         /:name/
    output:            true
  featured_tags:
    permalink:         /tag-:name/
    output:            true
